HEADERS += \
    ../extensions/CCBReader/CCSpriteLoader.h \
    ../extensions/CCBReader/CCScrollViewLoader.h \
    ../extensions/CCBReader/CCScale9SpriteLoader.h \
    ../extensions/CCBReader/CCParticleSystemQuadLoader.h \
    ../extensions/CCBReader/CCNodeLoaderListener.h \
    ../extensions/CCBReader/CCNodeLoaderLibrary.h \
    ../extensions/CCBReader/CCNodeLoader.h \
    ../extensions/CCBReader/CCMenuLoader.h \
    ../extensions/CCBReader/CCMenuItemLoader.h \
    ../extensions/CCBReader/CCMenuItemImageLoader.h \
    ../extensions/CCBReader/CCLayerLoader.h \
    ../extensions/CCBReader/CCLayerGradientLoader.h \
    ../extensions/CCBReader/CCLayerColorLoader.h \
    ../extensions/CCBReader/CCLabelTTFLoader.h \
    ../extensions/CCBReader/CCLabelBMFontLoader.h \
    ../extensions/CCBReader/CCControlLoader.h \
    ../extensions/CCBReader/CCControlButtonLoader.h \
    ../extensions/CCBReader/CCBSelectorResolver.h \
    ../extensions/CCBReader/CCBReader.h \
    ../extensions/CCBReader/CCBMemberVariableAssigner.h \
    ../extensions/CCBReader/CCBFileLoader.h \
    ../extensions/CCControlExtension/CCSpacer.h \
    ../extensions/CCControlExtension/CCScale9Sprite.h \
    ../extensions/CCControlExtension/CCMenuPassive.h \
    ../extensions/CCControlExtension/CCInvocation.h \
    ../extensions/CCControlExtension/CCControlUtils.h \
    ../extensions/CCControlExtension/CCControlSwitch.h \
    ../extensions/CCControlExtension/CCControlSlider.h \
    ../extensions/CCControlExtension/CCControlSaturationBrightnessPicker.h \
    ../extensions/CCControlExtension/CCControlHuePicker.h \
    ../extensions/CCControlExtension/CCControlExtensions.h \
    ../extensions/CCControlExtension/CCControlColourPicker.h \
    ../extensions/CCControlExtension/CCControlButton.h \
    ../extensions/CCControlExtension/CCControl.h \
    ../extensions/CCListView/CCListViewCell.h \
    ../extensions/CCListView/CCListView.h \
    ../extensions/CCListView/CCControlDefine.h \
    ../extensions/CCNotificationCenter/CCNotificationCenter.h \
    ../extensions/CCScrollView/CCScrollView.h \
    ../extensions/CCTextureWatcher/CCTextureWatcher.h

SOURCES += \
    ../extensions/CCBReader/CCSpriteLoader.cpp \
    ../extensions/CCBReader/CCScrollViewLoader.cpp \
    ../extensions/CCBReader/CCScale9SpriteLoader.cpp \
    ../extensions/CCBReader/CCParticleSystemQuadLoader.cpp \
    ../extensions/CCBReader/CCNodeLoaderLibrary.cpp \
    ../extensions/CCBReader/CCNodeLoader.cpp \
    ../extensions/CCBReader/CCMenuItemLoader.cpp \
    ../extensions/CCBReader/CCMenuItemImageLoader.cpp \
    ../extensions/CCBReader/CCLayerLoader.cpp \
    ../extensions/CCBReader/CCLayerGradientLoader.cpp \
    ../extensions/CCBReader/CCLayerColorLoader.cpp \
    ../extensions/CCBReader/CCLabelTTFLoader.cpp \
    ../extensions/CCBReader/CCLabelBMFontLoader.cpp \
    ../extensions/CCBReader/CCControlLoader.cpp \
    ../extensions/CCBReader/CCControlButtonLoader.cpp \
    ../extensions/CCBReader/CCBReader.cpp \
    ../extensions/CCBReader/CCBFileLoader.cpp \
    ../extensions/CCControlExtension/CCSpacer.cpp \
    ../extensions/CCControlExtension/CCScale9Sprite.cpp \
    ../extensions/CCControlExtension/CCMenuPassive.cpp \
    ../extensions/CCControlExtension/CCInvocation.cpp \
    ../extensions/CCControlExtension/CCControlUtils.cpp \
    ../extensions/CCControlExtension/CCControlSwitch.cpp \
    ../extensions/CCControlExtension/CCControlSlider.cpp \
    ../extensions/CCControlExtension/CCControlSaturationBrightnessPicker.cpp \
    ../extensions/CCControlExtension/CCControlHuePicker.cpp \
    ../extensions/CCControlExtension/CCControlColourPicker.cpp \
    ../extensions/CCControlExtension/CCControlButton.cpp \
    ../extensions/CCControlExtension/CCControl.cpp \
    ../extensions/CCListView/CCListViewCell.cpp \
    ../extensions/CCListView/CCListView.cpp \
    ../extensions/CCNotificationCenter/CCNotificationCenter.cpp \
    ../extensions/CCScrollView/CCScrollView.cpp \
    ../extensions/CCTextureWatcher/CCTextureWatcher.cpp
